name: visitor
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  graphql_flutter: ^5.1.2
  get: ^4.7.2
  connectivity_plus: ^6.1.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  http: ^1.3.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Png/
    - assets/Svg/
